# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
        working-directory: ./dummy-package-2.4.4
      - name: Create .tgz file
        run: npm pack

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "npm"
          owner: "interview-varun-gandhi"
          repo: "cloudsmith-ci-cd-assessment"
          republish: "true" # needed ONLY if version is not changing
          file: "*.tgz" # Ensure this matches the zip file created in the build step