# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
        working-directory: ./dummy-package
      - name: Create .tgz file
        run: npm pack
        working-directory: ./dummy-package
      - name: Upload .tgz artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-tgz
          path: ./dummy-package/*.tgz

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download .tgz artifact
        uses: actions/download-artifact@v4
        with:
          name: package-tgz
          path: ./dummy-package
      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "npm"
          owner: "workspace-for-interview-varun"
          repo: "cloudsmith-ci-cd-assessment"
          republish: "true" # needed ONLY if version is not changing
          file:  "./dummy-package/*.tgz" # Ensure this matches the zip file created in the build step
          